import { z } from "zod"
import { uploadSlackFile } from "../../../../src/integrations/slack/client"
import {
  relayAuth,
  relayDeviceAuthorized,
  relayUnauthorized,
} from "../../../../src/relay/auth"
import { azureRelayStore } from "../../../../src/relay/azure-store"

const HeadersSchema = z.object({
  artifactKey: z.string().min(1).max(160),
  contentLength: z.coerce.number().int().nonnegative().max(25 * 1024 * 1024),
  deviceId: z.uuid(),
  filename: z.string().min(1).max(1_024),
  jobId: z.uuid(),
  mimeType: z
    .string()
    .min(1)
    .max(255)
    .regex(/^[\w!#$&^_.+-]+\/[\w!#$&^_.+-]+$/),
})

function decodedFilename(value: string | null): string {
  let decoded: string
  try {
    decoded = decodeURIComponent(value ?? "")
  } catch {
    return ""
  }
  return [...decoded]
    .map((character) => {
      const code = character.charCodeAt(0)
      return code < 32 || code === 127 || '/\\";'.includes(character)
        ? "_"
        : character
    })
    .join("")
}

export const dynamic = "force-dynamic"
export const maxDuration = 120
export const runtime = "nodejs"

export async function POST(request: Request): Promise<Response> {
  const auth = relayAuth(request)
  if (!auth) return relayUnauthorized()
  const input = HeadersSchema.parse({
    artifactKey: request.headers.get("x-mako-artifact-key"),
    contentLength: request.headers.get("content-length"),
    deviceId: request.headers.get("x-mako-device-id"),
    filename: decodedFilename(request.headers.get("x-mako-filename")),
    jobId: request.headers.get("x-mako-job-id"),
    mimeType: request.headers.get("content-type"),
  })
  if (!relayDeviceAuthorized(auth, input.deviceId)) return relayUnauthorized()
  if (!request.body)
    return Response.json({ error: "A file body is required" }, { status: 400 })
  const target = await azureRelayStore.artifactTarget(input)
  if (target.uploaded) return Response.json({ ok: true, uploaded: false })
  if (target.payload.origin.provider !== "slack")
    return Response.json({ error: "No artifact adapter" }, { status: 400 })
  let received = 0
  const source = request.body.pipeThrough(
    new TransformStream<Uint8Array, Uint8Array>({
      transform(chunk, controller) {
        received += chunk.byteLength
        if (received > input.contentLength) {
          controller.error(new Error("Artifact exceeded its declared size"))
          return
        }
        controller.enqueue(chunk)
      },
      flush(controller) {
        if (received !== input.contentLength)
          controller.error(new Error("Artifact did not match its declared size"))
      },
    })
  )
  await uploadSlackFile({
    source,
    size: input.contentLength,
    mimeType: input.mimeType,
    channel: target.payload.origin.conversationId,
    filename: input.filename,
    initialComment: `Generated by ${target.payload.selection.harness ?? "Mako"}`,
    threadTs: target.payload.origin.threadId,
  })
  await azureRelayStore.markArtifactUploaded(input)
  return Response.json({ ok: true, uploaded: true })
}
