import { z } from "zod"
import { uploadSlackFile } from "../../../../src/integrations/slack/client"
import {
  relayAuth,
  relayDeviceAuthorized,
  relayUnauthorized,
} from "../../../../src/relay/auth"
import { azureRelayStore } from "../../../../src/relay/azure-store"

const FieldsSchema = z.object({
  artifactKey: z.string().min(1).max(128),
  deviceId: z.uuid(),
  jobId: z.uuid(),
})

export const dynamic = "force-dynamic"
export const maxDuration = 60
export const runtime = "nodejs"

export async function POST(request: Request): Promise<Response> {
  const auth = relayAuth(request)
  if (!auth) return relayUnauthorized()
  const form = await request.formData()
  const input = FieldsSchema.parse({
    artifactKey: form.get("artifactKey"),
    deviceId: form.get("deviceId"),
    jobId: form.get("jobId"),
  })
  if (!relayDeviceAuthorized(auth, input.deviceId)) return relayUnauthorized()
  const file = form.get("file")
  if (!(file instanceof File))
    return Response.json({ error: "A file is required" }, { status: 400 })
  if (file.size > 25 * 1024 * 1024)
    return Response.json({ error: "File exceeds 25 MB" }, { status: 413 })
  const target = await azureRelayStore.artifactTarget(input)
  if (target.uploaded) return Response.json({ ok: true, uploaded: false })
  if (target.payload.origin.provider !== "slack")
    return Response.json({ error: "No artifact adapter" }, { status: 400 })
  await uploadSlackFile({
    bytes: new Uint8Array(await file.arrayBuffer()),
    channel: target.payload.origin.conversationId,
    filename: file.name,
    initialComment: `Generated by ${target.payload.selection.harness ?? "Mako"}`,
    threadTs: target.payload.origin.threadId,
  })
  await azureRelayStore.markArtifactUploaded(input)
  return Response.json({ ok: true, uploaded: true })
}
