import type {
  HarnessModel as SharedHarnessModel,
  HarnessProfile as SharedHarnessProfile,
} from "../../electron/shared.ts"

export type {
  AcpPermissionRequest,
  AcpPromptAttachment,
  AcpSessionState,
  AcpUpdate,
  EntryBlock,
  Harness,
  Thread,
  ThreadEntry,
  ThreadRef,
  ThreadRunState,
  TurnUsage,
  Automation,
  AutomationRun,
  AutomationTrigger,
  Block,
  BlockType,
  BootPayload,
  Capabilities,
  ChatRole,
  CommandSummary,
  ContextUsage,
  DevServerState,
  ExternalEditor,
  FileContents,
  GitCommitEntry,
  GitDiff,
  GitFile,
  GitFileStatus,
  GitStatus,
  ListeningPort,
  GitHubStatus,
  CheckSummary,
  PullRequest,
  ReviewSummary,
  HostEvent,
  IntegrationCatalogSnapshot,
  IntegrationCategory,
  IntegrationConnection,
  IntegrationRecord,
  HarnessModel,
  HarnessModelOption,
  HarnessModelVariant,
  HarnessProfile,
  HarnessSelectValue,
  ModelCost,
  ModelInfo,
  MakoComputerPermissions,
  McpProvider,
  McpRegistryProviderStatus,
  McpRegistrySnapshot,
  McpScope,
  McpServerDefinition,
  McpServerOrigin,
  McpServerRecord,
  McpSyncPreview,
  McpSyncTarget,
  McpTransport,
  FileMatches,
  SearchOptions,
  SearchResults,
  SkillOrigin,
  SkillProvider,
  SkillProviderStatus,
  SkillRecord,
  SkillRegistrySnapshot,
  SkillScope,
  SkillSyncPreview,
  SkillSyncTarget,
  ThreadMatches,
  ChatMessage,
  SessionMeta,
  SessionState,
  SessionSummary,
  SkillSummary,
  StagedFile,
  TabSnapshot,
  TerminalCreateOptions,
  TerminalEvent,
  TerminalSession,
  TerminalSessionStatus,
  TerminalSnapshot,
  ThinkingLevel,
  UpdateState,
  UsageSummary,
  UsageTotals,
  TokenStats,
  ToolSummary,
  TreeNode,
  WorkspaceFile,
} from "../../electron/shared.ts"

export {
  automationTriggerAvailable,
  THINKING_LEVELS,
} from "../../electron/shared.ts"

export function harnessModelByIdentity(
  profile: SharedHarnessProfile | undefined,
  identity: string | undefined
): SharedHarnessModel | undefined {
  if (!profile || !identity) return undefined
  return profile.models.find(
    (model) =>
      model.id === identity ||
      model.launchId === identity ||
      model.aliases?.includes(identity)
  )
}
